Q.1 Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np

n_vector = np.zeros(10)
n_vector[4] = 1
print(n_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Q.2 Create a vector with values ranging from 10 to 49.

In [2]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Q.3 Create a 3x3 matrix with values ranging from 0 to 8.

In [5]:
value = np.arange(0,9)
matrix = value.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Q.4 Find indices of non-zero elements from [1,2,0,0,4,0].

In [6]:
array_1 = np.array([1,2,0,0,4,0])
nonzero_elements = np.nonzero(array_1)
print(nonzero_elements)

(array([0, 1, 4], dtype=int64),)


Q.5 Create a 10x10 array with random values and find the minimum and maximum values.

In [11]:
array_2 = np.random.rand(10,10)
min_value = np.min(array_2)
max_value = np.max(array_2)
print("Array : ", array_2)
print("Minimum Value : ", min_value)
print("Maximum Value : ", max_value)

Array :  [[0.2947426  0.99207363 0.9237201  0.09775897 0.58346908 0.2383964
  0.46622509 0.91660678 0.61532955 0.55487792]
 [0.71785764 0.79927392 0.75727339 0.33180448 0.65154501 0.73333969
  0.16455516 0.96834893 0.9061617  0.26160115]
 [0.17960949 0.82406656 0.1966428  0.07489553 0.37082106 0.94345121
  0.22144309 0.34849648 0.48662362 0.97409951]
 [0.84590804 0.24081507 0.73953812 0.10219562 0.8475617  0.52689304
  0.34119028 0.17603218 0.23596649 0.85634539]
 [0.90482071 0.58073842 0.40118992 0.74006568 0.18153226 0.31808623
  0.04128224 0.45440199 0.59874214 0.16310716]
 [0.8998532  0.82374713 0.31411688 0.14009789 0.33287951 0.20770117
  0.73711949 0.77619632 0.40835054 0.83691681]
 [0.8778737  0.27826623 0.71258722 0.55477098 0.94337479 0.80164091
  0.75083083 0.47038164 0.39033441 0.81894129]
 [0.93040076 0.27618173 0.14242704 0.8676206  0.27879312 0.61541287
  0.4286275  0.61333395 0.10136539 0.01737074]
 [0.74229225 0.00418555 0.89377237 0.40739614 0.42187438 0.05008808
  0.

Q.6 Create a random vector of size 30 and find the mean value.

In [15]:
Vector = np.random.random(30)
print("Array : ", Vector)
Mean_value = Vector.mean()
print("Mean Value of the Array : ",Mean_value)

Array :  [0.65410399 0.05993152 0.66697269 0.61804179 0.77297403 0.29702152
 0.33681248 0.16005617 0.26502368 0.55998991 0.41521847 0.81585841
 0.38584009 0.1369388  0.65051118 0.18657531 0.949323   0.51674484
 0.91212138 0.43973776 0.96696198 0.64959042 0.79167151 0.06368304
 0.32324383 0.15053426 0.28177478 0.77102293 0.24136126 0.07975644]
Mean Value of the Array :  0.47064658335118387
